# Generated by Django 5.0.4 on 2024-04-22 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('success', models.BooleanField(default=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.userapikey')),
            ],
        ),
    ]
